### ISSUE TITLE
Stub Mode for Optical Delay Line

### ISSUE THREAD

**Issue by zigen** [moonshot-nagayama-pj/PnPQ#20]
In order to aid future integration testing and help learn more about how our hardware works, we are building "stub" versions of devices. These do not connect to real hardware, but instead mimic or mock the behavior of those devices in code.

Later on, this will help us define common interfaces for devices, instead of the device-specific interfaces that we have now. It may also help us find better ways to refactor our existing code.

## Acceptance criteria

* Stub ODL has same public interface as [the Thorlabs ODL](https://github.com/moonshot-nagayama-pj/PnPQ/blob/main/src/pnpq/devices/odl_thorlabs_kbd101.py)
* Stub switch behavior reflects happy-path behavior for the Thorlabs ODL. In other words, the stub replicates the same behavior as the real switch when the switch does not produce any errors.
* All methods have type hints for input variables and return values.
* All public methods have basic docstring documentation explaining the method's behavior clearly. The class may also have docstring documentation.
* Any unclear variables or code is adequately commented.
* `pytest` unit tests are written for all public methods, with meaningful inputs

A good example of a pull request which fulfills all of these acceptance criteria is https://github.com/moonshot-nagayama-pj/PnPQ/pull/23

**Comment by auspicacious** [comment]
Closing this issue. We will re-evaluate the stub approach after we finish re-implementing the Thorlabs device drivers.
