### ISSUE TITLE
Fix waveplate custom home behavior

### ISSUE THREAD

**Issue by auspicacious** [moonshot-nagayama-pj/PnPQ#30]
While implementing the stub functionality in https://github.com/moonshot-nagayama-pj/PnPQ/issues/19 , we discovered that the behavior of the `custom_home` and `custom_rotate` functionality might not work as it should.

Essentially, it is not possible to rotate to all values from `custom_home`. For example, if `custom_home` is 90 degrees, and `custom_rotate` is called with 330 degrees, this will not work, because it surpasses 360 degrees on the absolute scale.

We should determine if we need this functionality and, if we do need it, fix it.

## Acceptance criteria

* This bug is fixed or the functionality is removed
* Clear docstring documentation is in place for these functions
* Unit tests are in place to exercise this code and validate all corner cases

**Comment by wiredinhp** [comment]
@auspicacious Hi there ! I am a new contributor to this repository and would love to contribute by solving this issue. Could you please assign this issue to me ?

**Comment by auspicacious** [comment]
Hi @wiredinhp , if you would like to implement this for the "stub" waveplate, please go ahead. You will need to know how to use [`rye`](https://rye.astral.sh/guide/) to build and test our project.

**Comment by auspicacious** [comment]
Hi @wiredinhp , I'm not sure if you were able to pick this up. If I don't hear from you within a couple of days, I will unassign this task from you and assign it to someone else.

**Comment by auspicacious** [comment]
Closing this, as the rewrite started in https://github.com/moonshot-nagayama-pj/PnPQ/issues/51 will obsolete this.
