### ISSUE TITLE
Standardized validation of pull requests for PnPQ

### ISSUE THREAD

**Issue by auspicacious** [moonshot-nagayama-pj/PnPQ#31]
See the parent epic for details and acceptance criteria: https://github.com/moonshot-nagayama-pj/testbed-meta/issues/13

Most likely, this will be the first PR validation that we implement, which means it will help set the pattern for other repositories. After completing this work, we should update the epic with what we have learned.

**Comment by TomShen1234** [comment]
We should also fix the inconsistencies within the VSCode configurations as part of this.

**Comment by auspicacious** [comment]
Completed fixes in https://github.com/moonshot-nagayama-pj/PnPQ/pull/48
