### ISSUE TITLE
Publish Sphinx-generated documentation website

### ISSUE THREAD

**Issue by auspicacious** [moonshot-nagayama-pj/PnPQ#78]
In https://github.com/moonshot-nagayama-pj/PnPQ/issues/71 , we started generating documentation using Sphinx.

We should publish that documentation automatically. This task should determine where we want to push it and how. GitHub Pages and ReadTheDocs are leading candidates for the "where;" GitHub Actions is the obvious choice for "how."

## Acceptance criteria
* Documentation is generated and uploaded to a public website on each push to `main` automatically.
* The README is updated to point to this documentation.

## Other considerations
* The documentation does not need to be versioned, yet, but after we begin publishing releases to PyPI it would be nice to be able to publish older versions of the documentation alongside the most recent.

**Comment by TomShen1234** [comment]
Before I start implementing anything. I think we should confirm the method and tools to do this. 
Here's a really nice [GitHub action made by a community member](https://github.com/peaceiris/actions-gh-pages) that's relatively popular, although not so actively maintained, which publishes a static site to GitHub Pages.

The way this works is that it will create a `gh-page` branch in the repository, which can be hosted on Pages. I've seen this practice used by many tool, so I'm wondering if we should adopt this?

There are also some other ways, such as creating a new repo to just host the page, or having a `/docs` folder inside the current repo which contains the website. 

Thoughts?
(I'll tag @master-of-ppap along as well)

**Comment by auspicacious** [comment]
@TomShen1234 I notice that the top of that community GitHub action points to the official tools first.

I have never been a huge fan of the `gh-pages` branch approach, because it will bloat the size of your repository as time goes on.

How about using this workflow instead?

https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#creating-a-custom-github-actions-workflow-to-publish-your-site

This uses an official GitHub Action that creates an artifact -- I don't think it modifies any Git repository to publish. There should be a number of templates available that we can base our action on.
